version: "3.8"
services:
  hoarder-web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - ${DOCKER_PATH}/hoarder/data:/data
    ports:
      - ${WEB_PORT}:3000
    environment:
        MEILI_ADDR: http://hoarder-meilisearch:7700
        BROWSER_WEB_URL: http://hoarder-chrome:9222
      # OPENAI_API_KEY: ...
        DATA_DIR: /data
      # Vars
        HOARDER_VERSION: ${HOARDER_VERSION}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
    labels:
        - homepage.group=Misc.
        - homepage.name=Hoarder
        - homepage.icon=hoarder.png
        - homepage.href=http://${SERVER_IP}:${WEB_PORT}
        - homepage.description=Bookmarker Manager 

  hoarder-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  hoarder-meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - ${DOCKER_PATH}/hoarder/meilisearch:/meili_data