version: "3"
services:
    n8n:
        image: docker.n8n.io/n8nio/n8n
        container_name: n8n
        environment:
            - N8N_SECURE_COOKIE=false #disabled for access localhost, not recommended
        volumes:
            - ${DOCKER_PATH}/n8n:/home/node/.n8n
        ports:
            - ${N8N_PORT}:5678
        restart: unless-stopped