version: "3"
services:
    sonarr:
        image: cr.hotio.dev/hotio/sonarr
        container_name: sonarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK=${UMASK}
        volumes:
            - ${DOCKER_PATH}/sonarr:/config
            #- ${MEDIA_DISK}:/data
            - ${DATA}:/data
        ports:
            - "${SONARR_PORT}:8989"
        restart: unless-stopped
    radarr:
        image: cr.hotio.dev/hotio/radarr
        container_name: radarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK=${UMASK}
        volumes:
            - ${DOCKER_PATH}/radarr:/config
            - ${DATA}:/data
        ports:
            - "${RADARR_PORT}:7878"
        restart: unless-stopped
    tautulli:
        image: lscr.io/linuxserver/tautulli
        container_name: tautulli
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/tautulli/config:/config
            - ${DOCKER_PATH}/plex/Library/Application Support/Plex Media Server/Logs:/logs
        ports:
            - "${TAUTULLI_PORT}:8181"
        restart: unless-stopped
    plex:
        image: plexinc/pms-docker:plexpass
        container_name: plex
        environment:
            - PLEX_UID=1000
            - PLEX_GID=1000
            - TZ=${TZ}
            #- UMASK=${UMASK}
            - PLEX_CLAIM=${PLEX_CLAIM}
            - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
            - ALLOWED_NETWORKS=${PLEX_ALLOWED_NETWORKS}
        volumes:
            - ${DOCKER_PATH}/plex:/config
            - ${MEDIA_DISK}:/media
            - ${DATA}:/ssd
            - ${MEDIA_DISK}/transcode:/transcode
        ports:
            - "${PLEX_PORT1}:32400/tcp"
            - "${PLEX_PORT2}:1900/udp"
            - "${PLEX_PORT3}:3005/tcp"
            - "${PLEX_PORT4}:5353/udp"
            - "${PLEX_PORT5}:8324/tcp"
            - "${PLEX_PORT6}:32410/udp"
            - "${PLEX_PORT7}32412/udp"
            - "${PLEX_PORT8}:32413/udp"
            - "${PLEX_PORT9}:32414/udp"
            - "${PLEX_PORT10}:32469/tcp"
        devices:
            - /dev/dri:/dev/dri
        restart: unless-stopped
    prowlarr:
        image: cr.hotio.dev/hotio/prowlarr:testing
        container_name: prowlarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK=${UMASK}
        volumes:
            - ${DOCKER_PATH}/prowlarr:/config
        ports:
            - "${PROWLARR_PORT}:9696"
        restart: unless-stopped
    nzbget:
        image: lscr.io/linuxserver/nzbget
        container_name: nzbget
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/nzbget:/config
            - /mnt/ssd/downloads/usenet:/downloads/usenet
        ports:
            - "${NZBGET_PORT}:6789"
        restart: unless-stopped
    sabnzbd:
        image: lscr.io/linuxserver/sabnzbd
        container_name: sabnzbd
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/sabnzbd:/config
            - ${DATA}/usenet:/data/usenet
            # - /mnt/ssd/downloads:/downloads
        ports:
            - "${SABNZBD_PORT}:8080"
        restart: unless-stopped
    addarr:
        container_name: addarr
        image: waterboy1602/addarr
        restart: "no"
        network_mode: host
        volumes:
        - ${DOCKER_PATH}/addarr/config.yaml:/app/config.yaml:ro
        - ${DOCKER_PATH}/addarr/chatid.txt:/app/chatid.txt:rw
        - ${DOCKER_PATH}/addarr/admin.txt:/app/admin.txt:ro
        # - ${DOCKER_PATH}/addarr/allowlist.txt:/app/allowlist.txt:ro
        # - ${DOCKER_PATH}/addarr/logs:/app/logs:rw
    plexautolanguages:
        image: remirigal/plex-auto-languages:latest
        container_name: PlexAutoLanguages
        environment:
        - TZ=${TZ}
        volumes:
        # make sure you have a file named 'config.yaml' in the 'config' dir
        - ${DOCKER_PATH}/plexautolanguages/:/config
        restart: unless-stopped