version: "3"
services:
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        environment:
            - TZ=${TZ}
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_SCHEDULE=0 0 5 * * * #isso faria rodar todo dia 5 da manha
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped