version: "3"
services:
    nzbget:
        image: lscr.io/linuxserver/nzbget
        container_name: nzbget
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/nzbget:/config
            - ${MEDIA_DISK}/usenet:/data/nzbget/usenet
        ports:
            - "${NZBGET_PORT}:6789"
        restart: unless-stopped
    sabnzbd:
        image: lscr.io/linuxserver/sabnzbd
        container_name: sabnzbd
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/sabnzbd:/config
            - ${DATA}/sabnzbd/movies:/data/sabnzbd/movies
            - ${MEDIA_DISK}/sabnzbd/tv:/data/sabnzbd/tv
        ports:
            - "${SABNZBD_PORT}:8080"
        restart: unless-stopped
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/qbittorrent:/config
            - ${MEDIA_DISK}/downloads:/downloads
            - ${DATA}/:/data
        ports:
            - "${QBITTORRENT_PORT1}:${QBITTORRENT_PORT1}"
            - "${QBITTORRENT_PORT2}:${QBITTORRENT_PORT2}"
            - "${QBITTORRENT_PORT2}:${QBITTORRENT_PORT2}/udp"
        restart: unless-stopped