version: "3"
services:
    freshrss:
        image: lscr.io/linuxserver/freshrss:latest
        container_name: freshrss
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/freshrss:/config
        ports:
            - "${FRESHRSS_PORT}:80"
        restart: unless-stopped

    fullfeedrss:
        image: 'heussd/fivefilters-full-text-rss:latest'
        environment:
            # Leave empty to disable admin section
            - FTR_ADMIN_PASSWORD=
        volumes:
            - '${DOCKER_PATH}/fullfeedrss:/var/www/html/cache/rss'
        ports:
            - '${FULLFEED_PORT}:80'
        restart: unless-stopped

    miniflux:
        image: miniflux/miniflux:latest
        ports:
        - "${MINIFLUXDB_PORT}:8080"
        depends_on:
            - miniflux-db
        environment:
            - DATABASE_URL=postgres://${MINIFLUXDB_USER}:${MINIFLUXDB_PASS}@miniflux-db/miniflux?sslmode=disable
            - RUN_MIGRATIONS=1
            - CREATE_ADMIN=1
            - ADMIN_USERNAME=${MINIFLUX_USER}
            - ADMIN_PASSWORD=${MINIFLUX_PASS}
    miniflux-db:
        image: postgres:15
        environment:
            - POSTGRES_USER=${MINIFLUXDB_USER}
            - POSTGRES_PASSWORD=${MINIFLUXDB_PASS}
            - POSTGRES_DB=miniflux
        volumes:
            - ${DOCKER_PATH}/miniflux-db:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "miniflux"]
            interval: 10s
            start_period: 30s