version: "3"
services:
    freshrss:
        image: lscr.io/linuxserver/freshrss:latest
        container_name: freshrss
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/freshrss:/config
        ports:
            - "${FRESHRSS_PORT}:80"
        restart: unless-stopped

    fullfeedrss:
        image: 'heussd/fivefilters-full-text-rss:latest'
        environment:
            # Leave empty to disable admin section
            - FTR_ADMIN_PASSWORD=
        volumes:
            - '${DOCKER_PATH}/fullfeedrss:/var/www/html/cache/rss'
        ports:
            - '${FULLFEED_PORT}:80'
        restart: unless-stopped