version: "3"
services:

    fullfeedrss:
        image: 'heussd/fivefilters-full-text-rss:latest'
        environment:
            # Leave empty to disable admin section
            - FTR_ADMIN_PASSWORD=${FTR_PASSWORD}
        volumes:
            - '${DOCKER_PATH}/fullfeedrss:/var/www/html/cache/rss'
        ports:
            - '${FULLFEED_PORT}:80'
        restart: unless-stopped
        labels:
            - homepage.group=RSS/Feed
            - homepage.name=FullFeed-RSS
            - homepage.icon=mdi-alpha-f-box-outline
            - homepage.href=http://${SERVER_IP}:${FULLFEED_PORT}
            - homepage.description=Convert text to RSS

    miniflux:
        image: miniflux/miniflux:latest
        ports:
        - "${MINIFLUXDB_PORT}:8080"
        depends_on:
            - miniflux-db
        environment:
            - DATABASE_URL=postgres://${MINIFLUXDB_USER}:${MINIFLUXDB_PASS}@miniflux-db/miniflux?sslmode=disable
            - RUN_MIGRATIONS=1
            - CREATE_ADMIN=1
            - ADMIN_USERNAME=${MINIFLUX_USER}
            - ADMIN_PASSWORD=${MINIFLUX_PASS}
        labels:
            - homepage.group=RSS/Feed
            - homepage.name=Miniflux
            - homepage.icon=miniflux.png
            - homepage.href=http://${SERVER_IP}:${MINIFLUXDB_PORT}
            - homepage.description=Minimalist RSS reader

    miniflux-db:
        image: postgres:15
        environment:
            - POSTGRES_USER=${MINIFLUXDB_USER}
            - POSTGRES_PASSWORD=${MINIFLUXDB_PASS}
            - POSTGRES_DB=miniflux
        volumes:
            - ${DOCKER_PATH}/miniflux-db:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "miniflux"]
            interval: 10s
            start_period: 30s