version: "3"
services:
    sonarr:
        image: ghcr.io/hotio/sonarr
        container_name: sonarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK=${UMASK}
        volumes:
            - ${DOCKER_PATH}/sonarr:/config
            - ${MEDIA_DISK}:/data
            #- ${DATA}:/data
        ports:
            - "${SONARR_PORT}:8989"
        restart: unless-stopped
    radarr:
        image: ghcr.io/hotio/radarr
        container_name: radarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK=${UMASK}
        volumes:
            - ${DOCKER_PATH}/radarr:/config
            - ${DATA}:/data
        ports:
            - "${RADARR_PORT}:7878"
        restart: unless-stopped
    prowlarr:
        image: ghcr.io/hotio/prowlarr
        container_name: prowlarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK=${UMASK}
        volumes:
            - ${DOCKER_PATH}/prowlarr:/config
        ports:
            - "${PROWLARR_PORT}:9696"
        restart: unless-stopped