version: "3"
services:
    sonarr:
        image: ghcr.io/hotio/sonarr
        container_name: sonarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK=${UMASK}
        volumes:
            - ${DOCKER_PATH}/sonarr:/config
            - ${MEDIA_DISK}:/data
            #- ${DATA}:/data
        ports:
            - "${SONARR_PORT}:8989"
        restart: unless-stopped
        labels:
            - homepage.group=Media
            - homepage.name=Sonarr
            - homepage.icon=sonarr.png
            - homepage.href=http://${SERVER_IP}:${SONARR_PORT}
            - homepage.description=Automate TV shows
            - homepage.widget.type=sonarr
            - homepage.widget.url=http://${SERVER_IP}:${SONARR_PORT}
            - homepage.widget.key=${SONARR_API}
            #- homepage.widget.fields=["field1","field2"] # optional

    radarr:
        image: ghcr.io/hotio/radarr
        container_name: radarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK=${UMASK}
        volumes:
            - ${DOCKER_PATH}/radarr:/config
            - ${DATA}:/data
        ports:
            - "${RADARR_PORT}:7878"
        restart: unless-stopped
        labels:
            - homepage.group=Media
            - homepage.name=Radarr
            - homepage.icon=radarr.png
            - homepage.href=http://${SERVER_IP}:${RADARR_PORT}
            - homepage.description=Automate Movies
            - homepage.widget.type=radarr
            - homepage.widget.url=http://${SERVER_IP}:${RADARR_PORT}
            - homepage.widget.key=${RADARR_API}

    prowlarr:
        image: ghcr.io/hotio/prowlarr
        container_name: prowlarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK=${UMASK}
        volumes:
            - ${DOCKER_PATH}/prowlarr:/config
        ports:
            - "${PROWLARR_PORT}:9696"
        restart: unless-stopped
        labels:
            - homepage.group=Media
            - homepage.name=Prowlarr
            - homepage.icon=prowlarr.png
            - homepage.href=http://${SERVER_IP}:${PROWLARR_PORT}
            - homepage.description=Manage indexers