version: "3"
services:
    maintainerr:
        image: ghcr.io/jorenn92/maintainerr:latest
        container_name: maintainerr
        environment:
            - TZ=${TZ}
            - UMASK=${UMASK}
        volumes:
            - ${DOCKER_PATH}/maintainerr:/opt/data
            #- ${DATA}:/data
        ports:
            - "6246:6246"
        restart: unless-stopped
        labels:
            - homepage.group=Automation
            - homepage.name=Maintainerr
            - homepage.icon=mdi-size-m
            - homepage.href=http://${SERVER_IP}:6246
            - homepage.description=Auto delete watched media